name: fledge_ecs_annotations
description: Annotations for the Fledge ECS framework. Used with fledge_ecs_generator for code generation.
version: 0.1.4
repository: https://github.com/fledge-framework/fledge/tree/main/packages/fledge_ecs_annotations
homepage: https://fledge-framework.dev
issue_tracker: https://github.com/fledge-framework/fledge/issues

environment:
  sdk: ^3.6.0

resolution: workspace

topics:
  - ecs
  - game-engine
  - game-development
  - annotations
