name: fledge_ecs_generator
description: Code generator for the Fledge ECS framework. Generates component registration and system wrappers.
version: 0.1.4
repository: https://github.com/fledge-framework/fledge/tree/main/packages/fledge_ecs_generator
homepage: https://fledge-framework.dev
issue_tracker: https://github.com/fledge-framework/fledge/issues

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.3
  source_gen: ^4.1.1
  fledge_ecs_annotations: ^0.1.2

dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  test: any
  lints: ^6.0.0

topics:
  - ecs
  - code-generation
  - build-runner
  - game-development
